#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# Get the number of new e-mails from one's GMail account
# You need:
#  - a GPG key
#  - to set ${GPGKEY} accordingly (e.g. ABCD1234)
#  - to set ${EMAIL} with your GMail e-mail address (e.g. bob@gmail.com)
#  - ~/.dotfiles/gmail.dat that can be generated by putting your password in
#    a file "my_file" and:
#        gpg --output ~/.dotfiles/gmail.dat -r ${GPGKEY} --encrypt my_file
#    Remember to delete "my_file" afterwards...

import sys, os, imaplib, subprocess

port = 993
server = 'imap.gmail.com'

# Find username
username = os.environ.get ('EMAIL')
if username == None:
    print ("Error: ${EMAIL} not set")
    sys.exit (1)

# Find GPG key
gpgkey = os.environ.get ('GPGKEY')
if gpgkey == None:
    print ("Error: ${GPGKEY} not set")
    sys.exit (1)

# Decrypt password
encrypted_pw_fname="~/.dotfiles/gmail.dat"
passwd=""
if not os.path.isfile (encrypted_pw_fname):
    proc = subprocess.Popen (["gpg -q --no-tty --use-agent --batch -r "
                              + gpgkey + " --decrypt " + encrypted_pw_fname],
                             stdout=subprocess.PIPE, shell=True)
    (passwd, err) = proc.communicate()

    if passwd == "":
        print ("Error: could not decrypt password (" + encrypted_pw_fname + ")")
        sys.exit (1)

    # Strip '\n'
    passwd = passwd.strip ()
else:
    print ("Error: missing GPG encrypted password (" + encrypted_pw_fname + ")")
    sys.exit (1)

# Prepare connection to IMAP server
imap_server = imaplib.IMAP4_SSL (server, port)

# Try to log in
try:
    imap_server.login (username, passwd)
except:
    # Error: check that IMAP is activated in GMail
    print ('Error: login error (' + str(sys.exc_info()[1]) + ')')
    sys.exit (1)

typ, data = imap_server.select ('Inbox', True)
if typ == 'OK':
    total = int (data[0])
    typ, data = imap_server.search (None, 'SEEN')
    if typ == 'OK':
        seen = len (data[0].split ())
        print('{} new'.format (total - seen))

if typ != 'OK':
    print ('?? new')

imap_server.logout ()
